test

diff --git a/.github/workflows/test_parallelism.yml b/.github/workflows/test_parallelism.yml
--- a/.github/workflows/test_parallelism.yml
+++ b/.github/workflows/test_parallelism.yml
@@ -47,3 +47,16 @@ jobs:
       - name: Run GPU Test
         if: matrix.job == 'gpu-test'
         uses: ./.github/actions/gpu-test
+
+  strategy:
+    needs: [ci]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail
+        run: |
+          if [ "${{ needs.ci.result }}" != "success" ]; then
+            echo "failed"
+            exit 1
+          else
+            exit 0
+          fi
